<?php
    $_productCollection=$this->getProductCollection();
    $_helper = $this->helper('catalog/output');
?>
    <?php if(!$_productCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
    <section id="bestselingproduct">
      <div class="sectiontitle">
        <h2><span>BEST SELLINGS</span></h2>
        <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).Mage::helper('extension')->getCustomUrl('bestselling')?>">View More Products</a>
<!--         <ul class="brandsmenu smartphones">
            <li>
                <?php
                $_productCollectionbrand = $this->getLoadedProductCollectionbrand();
                $_helper = $this->helper('catalog/output');
                ?>
                <select onchange="getbrand()" id="brands">
                    <option value="0">Brands</option>
                    <?php
                    foreach ($_productCollectionbrand as $_brand):
                        ?>
                        <option value="<?php echo $_brand->option_id; ?>"><?php echo $_brand->name; ?></option>
<?php endforeach ?>
                </select>
            </li>
        </ul> -->
      </div>
      <div class="columnslider" id="bestselingproducts" data-items="4">

       <?php foreach ($_productCollection as $_product): ?>
        <div class="col-box" id="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
            <?php if (date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10)         
                     && date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)) { ?>
                     <span class="new">new</span>
                     <?php } ?>
          
          <div class="img-box"><div class="abs_center"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a></div></div>
          <div class="bottom-area">
          <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
          <?php $storeId = Mage::app()->getStore()->getId();
          $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)  ->load($_product->getId());
          ?>
           <?php if($summaryData['rating_summary'] != "" && $summaryData['rating_summary'] != 0 ): ?>
          <div class="ratings">
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $summaryData['rating_summary']; ?>%"></div>
            </div>
            <?php if($summaryData['reviews_count'] > 1) {?>
                    <span class="amount reviewscounttop">(<?php echo $summaryData['reviews_count']; ?> reviews)</span>
            <?php } else {?>
                    <span class="amount reviewscounttop">(<?php echo $summaryData['reviews_count']; ?> review)</span>
            <?php } ?>
          </div>
           <?php endif ?>

          <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($_product->getPrice(),true,false); ?></div>
          </div>
          </a>
          <div class="actions">
              <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                  <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                  <?php echo $this->getAddToCartUrl($_product) ?>
              <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                  <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
              <?php else: ?>
                  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
              <?php endif; ?>
          </div>
        </div>
      <?php endforeach ?>
      </div>
      <a data-id="bestselingproducts" class="loadmore smartphones" href="<?php echo Mage::helper('extension')->getCustomUrl('bestselling')?>">View All Products</a>
    </section>
  <?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>