<?php
    $_productCollection=$this->getProductCollection();
    $_helper = $this->helper('catalog/output');
?>
    <?php if(!$_productCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
		<section id="bestselingproduct">
			<div class="sectiontitle">
				<h2><span>BEST SELLINGS</span></h2>
				<a href="extension/index/seller/">View More Products</a>
				<ul class="brandsmenu smartphones">
					<li>
					<select>
						<option>Mobile & Tablets</option>
						<option value="">Samsung</option>
						<option value="">LG</option>
						<option value="">Sony</option>
						<option value="">Apple</option>
						<option value="">Microsoft</option>
					</select>
					</li>
				</ul>
			</div>
			<div class="columnslider" id="bestselingproducts">

			 <?php foreach ($_productCollection as $_product): ?>
				<div class="col-box" id="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
				    <?php if (date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10)         
                     && date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)) { ?>
                     <span class="new">new</span>
                     <?php } ?>
					
					<div class="img-box"><div class="abs_center"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a></div></div>
					<div class="bottom-area">
					<h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
					<?php
                      $storeId = Mage::app()->getStore()->getId();
                      $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)  ->load($_product->getId()); 

                      ?> 
                      <div class="ratings">
                      <?php if ($summaryData['rating_summary'] != '') {?>
                            <div class="rating-box">                            
                                <div class="rating" style="width:<?php echo $summaryData['rating_summary']; ?>%"></div> 
                            </div>
                            <span class="amount reviewscounttop">(<?php echo $summaryData['reviews_count']; ?> reviews)</span>
                            <?php } else {?>
                            <div class="rating-box">
                                 <div class="rating" style="width:0%"></div>
                            </div>
                            <?php } ?>
                            
                        </div>

					<div class="price"><?php echo number_format( $_product->getPrice(),'1','.',','); ?><i>AED</i></div>

					</div>
					</a>
				</div>
			<?php endforeach ?>
			</div>
			<a data-id="bestselingproducts" class="loadmore smartphones" href ="extension/index/seller/">View All Products</a>
		</section>
	<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
