		<section id="bestselingproduct">
			<div class="sectiontitle">
				<h2><span>BEST SELLINGS</span></h2>
				<a href="#">View More Products</a>
				<ul class="brandsmenu smartphones">
					<li>
					<select>
						<option>Mobile & Tablets</option>
						<option value="">Samsung</option>
						<option value="">LG</option>
						<option value="">Sony</option>
						<option value="">Apple</option>
						<option value="">Microsoft</option>
					</select>
					</li>
				</ul>
			</div>
			<div class="columnslider" id="bestselingproducts">
				<div class="col-box"><a href="#">
					<span class="new">new</span>
					<div class="img-box"><div class="abs_center"><img src="images/universal-car-wishield.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Universal Car Windshield</h4>
					<div class="rating"></div>
					<div class="price">20<i>AED</i></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="new">new</span>
					<div class="img-box"><div class="abs_center"><img src="images/universal-car-wishield.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Universal Car Windshield</h4>
					<div class="rating"></div>
					<div class="price">20<i>AED</i></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/bodysuspender.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Baby Suspenders</h4>
					<div class="rating"></div>
					<div class="price">20<i>AED</i></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/iphonecase.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Phone Case iPhone 6 Plus</h4>
					<div class="rating"></div>
					<div class="price">20<i>AED</i></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/mini-bluetooth-speaker.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Mini Bluetooth Speakers</h4>
					<div class="rating"></div>
					<div class="price">20<i>AED</i></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/mini-bluetooth-speaker.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Mini Bluetooth Speakers</h4>
					<div class="rating"></div>
					<div class="price">20<i>AED</i></div>
					</div>
					</a>
				</div>
			</div>
			<a data-id="bestselingproducts" class="loadmore smartphones">View All Products</a>
		</section>