	<section id="sponsors">
			<div class="sectiontitle">
				<h2><span>Our Brands</span></h2>
				<a href="#">View More Brands</a>
			</div>
			<div class="row">
			<div class="col-sm-2"><div class="sponsorlogo"><img src="images/logo_sharp.jpg"></div></div>
			<div class="col-sm-2"><div class="sponsorlogo"><img src="images/logo_toshiba.jpg"></div></div>
			<div class="col-sm-2"><div class="sponsorlogo"><img src="images/logo_phillips.jpg"></div></div>
			<div class="col-sm-2"><div class="sponsorlogo"><img src="images/logo_panasonic.jpg"></div></div>
			<div class="col-sm-2"><div class="sponsorlogo"><img src="images/logo_sony.jpg"></div></div>
			<div class="col-sm-2"><div class="sponsorlogo"><img src="images/logo_electrolux.jpg"></div></div>
			</div>
		</section>