<?php $_Collection = $this->getLoadedProductCollection();
      $Collection = $this->getLoadedProductCollectionnew();
      $_helper = $this->helper('catalog/output');
      if($_Collection->count() || $Collection->count()):
?>
<section id="computeraccessories">
    <div class="sectiontitle">
        <h2><span>Computer & Accessories</span></h2>
        <ul class="brandsmenu desktop">
            <li><a onclick="newproduct1()" id="three">New Products</a></li>
            <li><a class="active" onclick="bestseller1()" id="four" >Best Sellers</a></li>
            <li>
               <?php
                $productCollectionbrand = $this->getproductbrands();
                $_helper = $this->helper('catalog/output');
                ?>
                <?php
                    foreach ($productCollectionbrand as $brand):
                        ?>
                        <?php $a[]= $brand->brand_optionid; ?>
                        <?php $b[] = $brand->brand_name; ?>
                    <?php endforeach ?>
                    <?php $optionid = array_unique($a); ?>
                    <?php $brandname = array_unique($b); ?>
                     <?php $max = sizeof($brandname); ?>
                <select onchange="getbrands()" id="brand">
                    <option value="0">Brands</option>
                    <?php for($i = 0; $i <= $max; $i++)
                             {?>
                                <?php if($optionid[$i] != ""){ ?>
                                <option value="<?php echo $optionid[$i]; ?>"><?php echo $brandname[$i]; ?></option>
                                <?php } ?>
                            <?php }
                    ?>
                </select>
            </li>
        </ul>
    </div>
    <div class="columnslider" id="bestseller1" data-items="4">
    </div>
    <div class="columnslider" id="newproduct1" data-items="4" >
    </div>
    <?php $url = Mage::getModel('catalog/category')->load(39)->getUrl();?>
    <div class="clearfix viewmore" align="right"><a href="<?php echo $url ?>">View All Products</a></div>
</section>

<script>
    function newproduct1() {
        jQuery('#bestseller1').hide();
        jQuery('#newproduct1').show();
        jQuery('#three').addClass("active");
        jQuery('#four').removeClass("active");

    }
    function bestseller1() {
        jQuery('#bestseller1').show();
        jQuery('#newproduct1').hide();
        jQuery('#four').addClass("active");
        jQuery('#three').removeClass("active");
    }

    jQuery(document).ready(function () {
        jQuery('#bestseller1').show();
        jQuery('#newproduct1').hide();
        jQuery('#four').addClass("active");
        jQuery('#three').removeClass("active");

        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestseller/',
            type: 'POST',
            data: {action: 'getLoadedProductCollection'},
            beforeSend: function () {
                jQuery('#bestseller1').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestseller1').html(data);
                //jQuery('#bestsejQueryller1').trigger('refresh.owl.carousel');
                reinitOwlOnSelector('#bestseller1',4);
            }
        });

        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxnewproduct/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionnew'},
            success: function (data) {

                jQuery('#newproduct1').html(data);
                reinitOwlOnSelector('#newproduct1',4);
            }
        });

    });

    function getbrands() {
        var brand = document.getElementById("brand").value
        
        //make the ajax call
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestseller/',
            type: 'POST',
            data: {action: 'getLoadedProductCollection', brands_ids: brand},
            beforeSend: function () {
                jQuery('#bestseller1').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestseller1').html(data);
                //jQuery('#bestsejQueryller1').trigger('refresh.owl.carousel');
                reinitOwlOnSelector('#bestseller1',4);
            }
        });

        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxnewproduct/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionnew', brands_ids: brand},
            success: function (data) {

                jQuery('#newproduct1').html(data);
                reinitOwlOnSelector('#newproduct1',4);
            }
        });
        
/*        jQuery(document).ready(function () {
            jQuery("#computeraccessories").on('change', function (e) {
                
            });
        });*/
//window.location =("index.php?brands_ids="+brand);
    }
</script>
<?php endif ?>