		<section id="computeraccessories">
			<div class="sectiontitle">
				<h2><span>COMPUTERS & Accessories</span></h2>
				<ul class="brandsmenu">
					<li><a href="#" class="active">New Products</a></li>
					<li><a href="#">Best Sellers</a></li>
					<li>
					<select>
						<option>Brands</option>
						<option value="">Samsung</option>
						<option value="">LG</option>
						<option value="">Sony</option>
						<option value="">Apple</option>
						<option value="">Microsoft</option>
					</select>
					</li>
				</ul>
			</div>
			<div class="columnslider" id="ComputerAccessories">
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/sony-vaio-laptop.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Sony Vaio Laptop</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<span class="new">new</span>
					<div class="img-box"><div class="abs_center"><img src="images/razor-mouse.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Razor Mouse</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/laptop-backpack.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Laptop Backpack</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/mac-book-air.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>MacBook Air</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/razor-mouse.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Razor Mouse</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
			</div>
			<div class="clearfix viewmore" align="right"><a href="#">View All Products</a></div>
		</section>