
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php foreach ($_productCollection as $_product): ?>
        <div>
            <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
                    <?php if (date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)) {
                        ?>
                        <span class="new">new</span>
                    <?php } ?>

                    <div class="img-box"><div class="abs_center"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                <?php $_imgSize = 210; ?>
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                            </a></div></div>
                    <div class="bottom-area">
                        <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4> 
                        <div class="price"><?php echo number_format($_product->getPrice(), '1', '.', ','); ?><i>AED</i></div>
                    </div>
                </a>
            </div>
        </div>
    <?php endforeach ?>
<?php endif; ?>
<script>
    //jQuery(document).ready(function () {
    /*jQuery("#computeraccessories").on('change', function (e) {
        jQuery('.columnslider').owlCarousel('destroy');
        alert("yoo");
        //$("#owl-demo").data('owlCarousel').destroy();
        var itemsShow = 4;
        jQuery(".columnslider").owlCarousel({
            items: itemsShow,
            dots: false,
            margin: 20,
            nav: true,
            responsiveClass: true,
            responsive: {
                0: {
                    items: 1,
                },
                480: {
                    items: 2,
                },
                768: {
                    items: 3,
                },
                1025: {
                    items: itemsShow,
                }
            }
        });
    });*/
    //});
</script>