<?php $_Collection = $this->getLoadedProductCollection();
      $Collection = $this->getLoadedProductCollectionnew();
      $_helper = $this->helper('catalog/output');
      if($_Collection->count() || $Collection->count()):
?>
<section id="perfumewatches">
    <div class="sectiontitle">
        <h2><span>Perfume & Watches</span></h2>
        <ul class="brandsmenu desktop">
            <li><a onclick="newproduct2()" id="five">New Products</a></li>
            <li><a class="active" onclick="bestseller2()" id="six" >Best Sellers</a></li>
            <li>
               <?php
                $productCollectionbrand = $this->getproductbrands();
                $_helper = $this->helper('catalog/output');
                ?>
                <?php
                    foreach ($productCollectionbrand as $brand):
                        ?>
                        <?php $a[]= $brand->brand_optionid; ?>
                        <?php $b[] = $brand->brand_name; ?>
                    <?php endforeach ?>
                    <?php $optionid = array_unique($a); ?>
                    <?php $brandname = array_unique($b); ?>
                     <?php $max = sizeof($brandname); ?>
                <select onchange="getbrands1()" id="brand1">
                    <option value="0">Brands</option>
                    <?php for($i = 0; $i <= $max; $i++)
                             {?>
                                <?php if($optionid[$i] != ""){ ?>
                                <option value="<?php echo $optionid[$i]; ?>"><?php echo $brandname[$i]; ?></option>
                                <?php } ?>
                            <?php }
                    ?>
                </select>
            </li>
        </ul>
    </div>
    <div class="columnslider" id="bestseller2" data-items="4">
        
    </div>
    <div class="columnslider" id="newproduct2" data-items="4" >
      
    </div>
    <?php $url = Mage::getModel('catalog/category')->load(65)->getUrl();?>
    <div class="clearfix viewmore" align="right"><a href="<?php echo $url ?>">View All Products</a></div>
</section>


<script>
    function newproduct2() {
        jQuery('#bestseller2').hide();
        jQuery('#newproduct2').show();
        jQuery('#five').addClass("active");
        jQuery('#six').removeClass("active");

    }
    function bestseller2() {
        jQuery('#bestseller2').show();
        jQuery('#newproduct2').hide();
        jQuery('#six').addClass("active");
        jQuery('#five').removeClass("active");
    }

    jQuery(document).ready(function () {
        jQuery('#bestseller2').show();
        jQuery('#newproduct2').hide();
        jQuery('#six').addClass("active");
        jQuery('#five').removeClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestsellerperfume/',
            type: 'POST',
            data: {action: 'getLoadedProductCollection'},
            beforeSend: function () {
                jQuery('#bestseller2').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestseller2').html(data);
                //jQuery('#bestsejQueryller1').trigger('refresh.owl.carousel');
                reinitOwlOnSelector('#bestseller2',4);
            }
        });

        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxnewproductperfume/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionnew'},
            success: function (data) {

                jQuery('#newproduct2').html(data);
                reinitOwlOnSelector('#newproduct2',4);
            }
        });

    });

    function getbrands1() {
        var brand = document.getElementById("brand1").value
        //make the ajax call
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestsellerperfume/',
            type: 'POST',
            data: {action: 'getLoadedProductCollection', brands_id: brand},
            beforeSend: function () {
                jQuery('#bestseller2').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestseller2').html(data);
                //jQuery('#bestsejQueryller1').trigger('refresh.owl.carousel');
                reinitOwlOnSelector('#bestseller2',4);
            }
        });

        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxnewproductperfume/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionnew', brands_id: brand},
            success: function (data) {

                jQuery('#newproduct2').html(data);
                reinitOwlOnSelector('#newproduct2',4);
            }
        });
        
/*        jQuery(document).ready(function () {
            jQuery("#computeraccessories").on('change', function (e) {
                
            });
        });*/
//window.location =("index.php?brands_ids="+brand);
    }
</script>
<?php endif ?>