<section id="phoneaccessories" class="desktop">
			<div class="sectiontitle">
				<h2><span>Phones & Accessories</span></h2>
				<ul class="brandsmenu">
					<li><a onclick="newproduct()" id="one">New Products</a></li>
					<li><a class="active" onclick="bestseller()" id="two" >Best Sellers</a></li>
					<li>
					<?php
                    $_productCollectionbrand=$this->getLoadedProductCollectionbrand();
                    $_helper = $this->helper('catalog/output');?>
					<select onchange="getbrand()" id="brands">
					<option value="0">Brands</option>
					<?php
                    foreach ($_productCollectionbrand as $_brand): 
                    ?>
						<option value="<?php echo $_brand->option_id; ?>"><?php echo $_brand->name; ?></option>
					<?php endforeach ?>
					</select>
					</li>
				</ul>
			</div>
			<div class="columnslider" id="bestseller">
			<?php
            $_productCollection=$this->getLoadedProductCollection();
            $_helper = $this->helper('catalog/output');
            ?>
            <?php if(!$_productCollection->count()): ?>
                <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
             <?php else: ?>
			 <?php foreach ($_productCollection as $_product): ?>
				<div class="col-box" id="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
				    <?php if (date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10)         
                     && date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)) { ?>
                     <span class="new">new</span>
                     <?php } ?>
					
					<div class="img-box"><div class="abs_center"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a></div></div>
					<div class="bottom-area">
					<h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4> 
                     <div class="price"><?php echo number_format( $_product->getPrice(),'1','.',','); ?><i>AED</i></div>
					</div>
					</a>
				</div>
			<?php endforeach ?>
			<?php endif; ?>
			</div>
			<div class="columnslider" id="newproduct">
				<?php
            $productCollection=$this->getLoadedProductCollectionnew();
            $_helper = $this->helper('catalog/output');
            ?>
            <?php if(!$productCollection->count()): ?>
                <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
             <?php else: ?>
			 <?php foreach ($productCollection as $_product): ?>
				<div class="col-box" id="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
				    <?php if (date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10)         
                     && date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)) { ?>
                     <span class="new">new</span>
                     <?php } ?>
					
					<div class="img-box"><div class="abs_center"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                    <?php $_imgSize = 210; ?>
                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                         src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </a></div></div>
					<div class="bottom-area">
					<h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4> 
                     <div class="price"><?php echo number_format( $_product->getPrice(),'1','.',','); ?><i>AED</i></div>
					</div>
					</a>
				</div>
			<?php endforeach ?>
			<?php endif; ?>
			<div class="clearfix viewmore" align="right"><a href="#">View All Products</a></div>
		</section>
		
		<script>
		function newproduct(){
            jQuery('#bestseller').hide();
            jQuery('#newproduct').show();
            jQuery('#one').addClass("active");
            jQuery('#two').removeClass("active");

		}
		function bestseller(){
            jQuery('#bestseller').show();
            jQuery('#newproduct').hide();
            jQuery('#two').addClass("active");
            jQuery('#one').removeClass("active");
		}

		jQuery( document ).ready(function() {
            jQuery('#bestseller').show();
            jQuery('#newproduct').hide();
            jQuery('#two').addClass("active");
            jQuery('#one').removeClass("active");

		});

		function getbrand(){
			var brand = document.getElementById("brands").value
			 //make the ajax call
             jQuery.ajax({
             url: 'extension/index/ajaxbestsellerphone/',
             type: 'POST',
             data: {action : 'getLoadedProductCollection' , brand_ids : brand},
             success: function(data) { 
          
             	jQuery('#bestseller').html(data);
             }
             });

             jQuery.ajax({
             url: 'extension/index/ajaxnewproductphone/',
             type: 'POST',
             data: {action : 'getLoadedProductCollectionnew' , brand_ids : brand},
             success: function(data) { 
          
             	jQuery('#newproduct').html(data);
             }
             });
		//window.location =("index.php?brands_ids="+brand);

		}
		</script>
