<section id="phoneaccessories" class="desktop">
			<div class="sectiontitle">
				<h2><span>Phones & Accessories</span></h2>
				<ul class="brandsmenu">
					<li><a href="#">New Products</a></li>
					<li><a href="#" class="active">Best Sellers</a></li>
					<li>
					<select>
						<option>Brands</option>
						<option value="">Samsung</option>
						<option value="">LG</option>
						<option value="">Sony</option>
						<option value="">Apple</option>
						<option value="">Microsoft</option>
					</select>
					</li>
				</ul>
			</div>
			<div class="columnslider">
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/samsung-galaxy-s6-tab.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Samsung Galaxy Tab 4 - 7″</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<span class="new">new</span>
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/hot-touch-slim-armor.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Hot Touch Slim Armor</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/pu-wallet-leather.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>PU Wallet Leather</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
			</div>
			<div class="clearfix viewmore" align="right"><a href="#">View All Products</a></div>
		</section>