<h3 class="heading2">Product Returns</h3>
<div class="col-sm-7 col-md-8 paddingzeroL contact-us">
<p>Please complete the form below to request an RMA number.</p>
<form class="form-horizontal" action="" method="">
<h3 class="heading3">Order Information</h3>
<div class="form-group">
<div class="col-sm-6"><input class="form-control" type="text" placeholder="First Name" required="" name="firstname" /></div>
<div class="col-sm-6"><input class="form-control" type="text" placeholder="First Name" required="" name="lastname" /></div>
</div>
<div class="form-group">
<div class="col-sm-6"><input class="form-control" type="text" placeholder="Order ID" required="" name="orderid" /></div>
<div class="col-sm-6"><input class="form-control" type="date" placeholder="Order Date" required="" name="orderdate" /></div>
</div>
<div class="form-group">
<div class="col-sm-6"><input class="form-control" type="email" placeholder="Email" required="" name="email" /></div>
<div class="col-sm-6"><input class="form-control" type="tel" placeholder="Telephone" required="" name="tel" /></div>
</div>
<h3 class="heading3">Product Information &amp; Reason for Return</h3>
<div class="form-group">
<div class="col-sm-4"><input class="form-control" type="text" placeholder="Product Name" required="" name="productname" /></div>
<div class="col-sm-4"><input class="form-control" type="text" placeholder="Product Code" required="" name="productcode" /></div>
<div class="col-sm-4"><input class="form-control" type="text" placeholder="Quantity" required="" name="quantity" /></div>
</div>
<div class="form-group">
<div class="col-sm-4">
<h4 class="heading4">Reason for Return</h4>
<label class="label"><input type="radio" required="" value="Dead On Arrival" name="returnresons" /> Dead On Arrival</label> <label class="label"><input type="radio" required="" value="Faulty, please supply details" name="returnresons" /> Faulty, please supply details</label> <label class="label"><input type="radio" required="" value="Order Error" name="returnresons" /> Order Error</label> <label class="label"><input type="radio" required="" value="Other, please supply details" name="returnresons" /> Other, please supply details</label> <label class="label"><input type="radio" required="" value="Received Wrong Item" name="returnresons" /> Received Wrong Item</label></div>
<div class="col-sm-4">
<h4 class="heading4">Product is opened</h4>
<label class="label"><input type="radio" required="" value="Yes" name="productopened" /> Yes</label> <label class="label"><input type="radio" required="" value="No" name="productopened" /> No</label><br /><br /> <label>Faulty or other details:</label> <textarea class="form-control" name="otherdetails"></textarea></div>
<div class="col-sm-4">
<h4 class="heading4">Enter the code in the box below</h4>
<input class="form-control" type="text" required="" name="captchacode" /></div>
</div>
<div class="form-group row">
<div class="col-sm-6">
<p>All Fields are Mandatory</p>
</div>
<div class="col-sm-6" style="text-align: right;"><button class="btn btn1" type="submit">Submit</button></div>
</div>
</form></div>
<div class="col-sm-5 col-md-4 paddingzeroR">
<div class="filters">
<h2>Customer Service</h2>
<div class="padding2">
<h5>TOLL FREE NO</h5>
<h3>800 42935</h3>
</div>
</div>
<div class="filters">
<h2>Follow Us</h2>
<div class="social padding2">&nbsp;</div>
</div>
<div class="filters">
<h2>Find Us on Map</h2>
<div class="padding2"><iframe style="border: 0;" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3608.311990276597!2d55.2914456!3d25.2600882!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f43159b182d3f%3A0x87c126f02847baef!2sHazel+Trading+LLC!5e0!3m2!1sen!2s!4v1437640330105" height="300" width="100%"></iframe></div>
</div>
</div>