		<section id="recomendations">
			<div class="sectiontitle">
				<h2><span>RECOMMENDATIONS FOR YOU</span></h2>
				<ul class="brandsmenu">
					<li><a href="#"><i class="fa fa-random"></i> Try Your Luck</a></li>
				</ul>
			</div>
			<div class="recomandations" id="recomandationsSection">
			<div class="row">
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/blue-dimond-ring.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">10 Orders</div>
					</div></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/hp-printer.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">50 Orders</div>
					</div></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/game-pad.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">05 Orders</div>
					</div></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/mx-hardisk.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">56 Orders</div>
					</div></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/boot.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">10 Orders</div>
					</div></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/ring-triditional.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">10 Orders</div>
					</div></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/shower.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">10 Orders</div>
					</div></a>
					</div>
				</div>
				<div class="col-sm-4 col-md-3 col-rec">
					<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/purse.jpg" alt=""></div></div>
					<div class="bottom-area">
					<div class="price">20<i>AED</i></div>
					<div class="orders">10 Orders</div>
					</div></a>
					</div>
				</div>
			</div>
			</div>
			<a data-id="recomandationsSection" class="loadmore smartphones">Load More</a>
		</section>