<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
    <?php if(!$_productCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
            <section id="deals">
			    <div class="sectiontitle">
				    <h2><span>TODAY'S DEALS</span></h2>			
				    <h4>Deals End in  <span>00:00:00</span></h4>
				    <a href="#">View More Products</a>
			    </div>
			    <div class="columnslider" id="sectionDeals">
			     <?php foreach ($_productCollection as $_product): ?>
				    <div class="col-box" id="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
				        <?php $special = $_product->getSpecialPrice();
				              $actual = $_product->getPrice();
				              $percent = ($special / $actual) * 100;
				              $percentFinal = 100 - $percent;  ?>
					    <span class="discount"><?php echo number_format($percentFinal,'1','.',',') ?>%</span>
					    <div class="img-box"><div class="abs_center"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a></div></div>
					        <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
					        <div class="price"><?php echo number_format($_product->getSpecialPrice(), '1','.',','); ?><i>AED</i> <span class="not-now"><?php echo number_format($_product->getPrice(),'1','.',','); ?><i>AED</i></span></div>
					</a></div>
					<?php endforeach ?>
				</div>
			<a data-id="sectionDeals" class="loadmore smartphones">Load More</a>
		</section>
		<?php endif; ?>