<section id="deals">
			<div class="sectiontitle">
				<h2><span>TODAY'S DEALS</span></h2>
				<h4>Deals End in  <span>00:00:00</span></h4>
				<a href="#">View More Products</a>
			</div>
			<div class="columnslider" id="sectionDeals">
				<div class="col-box"><a href="#">
					<span class="discount">43%</span>
					<div class="img-box"><div class="abs_center"><img src="<?php echo $this->getSkinUrl('images/headphone1.jpg'); ?>" alt=""></div></div>
					<div class="bottom-area">
					<h4>Beats Solo 2 Wireless</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">20%</span>
					<div class="img-box"><div class="abs_center"><img src="<?php echo $this->getSkinUrl('images/headphone1.jpg'); ?>" alt=""></div></div>
					<div class="bottom-area">
					<h4>iPAD Air (Retina)</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">15%</span>
					<div class="img-box"><div class="abs_center"><img src="<?php echo $this->getSkinUrl('images/headphone1.jpg'); ?>" alt=""></div></div>
					<div class="bottom-area">
					<h4>Mackbook Air (Retina)</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">08%</span>
					<div class="img-box"><div class="abs_center"><img src="<?php echo $this->getSkinUrl('images/headphone1.jpg'); ?>" alt=""></div></div>
					<div class="bottom-area">
					<h4>Beats Solo 2 Wireless</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">15%</span>
					<div class="img-box"><div class="abs_center"><img src="<?php echo $this->getSkinUrl('images/headphone1.jpg'); ?>" alt=""></div></div>
					<div class="bottom-area">
					<h4>Beats Solo 2 Wireless</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
			</div>
			<a data-id="sectionDeals" class="loadmore smartphones">Load More</a>
		</section>