<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $count = 1;
    $toDate = date('Y-m-d');
?>
    <?php if(!$_productCollection->count()): ?>
        <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php else: ?>
            <section id="deals">
			    <div class="sectiontitle">
				    <h2><span>TODAY'S DEALS</span></h2>
				    <h4>Deals End in <span id="countbox_<?php echo $count; ?>"></span> 
				    </h4>
				    <a href="extension/index/sale/">View More Products</a>
			    </div>
			    <div class="columnslider" id="sectionDeals" data-items="4">
			     <?php foreach ($_productCollection as $_product): ?>
				    <div class="col-box" id="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
				        <?php $special = $_product->getSpecialPrice();
				              $actual = $_product->getPrice();
				              $percent = ($special / $actual) * 100;
				              $percentFinal = 100 - $percent;  ?>
					    <span class="discount"><?php echo number_format($percentFinal,'1','.',',') ?>%</span>
					    <div class="img-box"><div class="abs_center"><!-- <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"> -->
                            <?php $_imgSize = 210; ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                             alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <!-- </a> --></div></div>
                        <div class="bottom-area">
				        <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
				        <div class="price"><?php echo number_format($_product->getSpecialPrice(), '1','.',','); ?><i>AED</i> <span class="not-now"><?php echo number_format($_product->getPrice(),'1','.',','); ?><i>AED</i></span></div>
					    </div>
					</a></div>
					<?php endforeach ?>
				</div>
			<a data-id="sectionDeals" class="loadmore smartphones">Load More</a>
		</section>

		<?php endif; ?>
		<script type="text/javascript">
	   var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)).' 11:59:00 PM'; ?>");
	   start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
	   start_date = Date.parse(start);
	   var dnow<?php echo $count; ?> = new Date(start_date);
	   if(CountStepper>0)
	   ddiff= new Date((dnow<?php echo $count; ?>)-(dthen<?php echo $count; ?>));
	   else
	   ddiff = new Date((dthen<?php echo $count; ?>)-(dnow<?php echo $count; ?>));
	   gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf()/1000);
	   var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
	   CountBack(gsecs<?php echo $count; ?>,"countbox_"+timer, timer);
	   timer++;
	</script>
<?php $count = $count + 1; ?>

<!--Dynamic style changes goes here-->
<?php 
	/* Admin Controllers for timer are declared here */
	$desc_color = Mage::getStoreConfig('timer/apptha_timer_color/description');
	$timer_color = Mage::getStoreConfig('timer/apptha_timer_color/text');
	$head_color = Mage::getStoreConfig('timer/apptha_timer_color/heading_text_color');
?>
<style>
    .timer-view{width : 56% ;padding:0;color: #<?php echo $timer_color; ?>;font-size: 20px; font-family: arial;font-weight: bold;}
    .timerdate{float: left;width: 100%;padding:0 0 15px 1px;color: #<?php echo $desc_color; ?>;font-size: 13px;}
    #heading1{color:#<?php echo $head_color;?>;}
</style>