<style>
	th,td{
		padding: 10px;
	}
</style>
<?php  $_order = $this->getOrder() ?>
<body style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<table  width="100%" id="my-orders-table" cellpadding="0" cellspacing="0"  summary="<?php echo $this->__('Items Ordered') ?>">
    <col />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr style="background: #EAEAEA">
			<th style="font-size:13px;padding:3px 9px" width="10%"></th>
            <th style="font-size:13px;padding:3px 9px" width="50%"><?php echo $this->__('Product Name') ?></th>
            <th style="font-size:13px;padding:3px 9px" width="10%"><?php echo $this->__('SKU') ?></th>
            <th style="font-size:13px;padding:3px 9px" width="10%"><?php echo $this->__('Price') ?></th>
		</tr>
    </thead>    
    <?php $_items = $_order->getItemsCollection(); ?>
    <?php $_index = 0; ?>
        <?php $_count = $_items->count(); ?>
	<tbody>
    <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getParentItem()) continue; ?>
        <tr>
			<td style="padding: 5px">			
				 <?php $_product = Mage::getModel('catalog/product')->load($_item->getProductId());?>
	           		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(64); ?>" width="64" height="64" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
				</a>
			</td>
			<td>
				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class=""><?php echo $_item->getName(); ?></a>
			</td>
			<td style="text-align: center"><?php echo $_item->getSku(); ?></td>
			<td style="text-align: center">
			<?php echo $this->getOrder()->formatPrice($_item->getPrice()) ?>
			</td>
		</tr>
    <?php endforeach; ?>
	</tbody>
</table>
</div>

</body>