<div class="page_menu desktop ">
	<a class="_mPS2id-h" href="#phoneaccessories" rel="m_PageScroll2id"> Phone &amp; Accessories</a>
	<a class="_mPS2id-h" href="#computeraccessories" rel="m_PageScroll2id"> Computer &amp; Accessories</a>
	<a class="_mPS2id-h mPS2id-highlight mPS2id-highlight-first mPS2id-highlight-last" href="#recomendations" rel="m_PageScroll2id"> Recomandations for you</a>
	<a class="_mPS2id-h" href="#deals" rel="m_PageScroll2id"> Super Deals</a>
	<a class="_mPS2id-h" href="#bestselingproduct" rel="m_PageScroll2id"> Best Selling</a>
	<a class="_mPS2id-h" href="#ads" rel="m_PageScroll2id"> Ads</a>
	<a class="_mPS2id-h" href="#menuslider" rel="m_PageScroll2id"> Featured Slider</a>
	<a class="_mPS2id-h" href="#buyersprotection" rel="m_PageScroll2id"> Buyers Protection</a>
	<a class="_mPS2id-h" href="#features" rel="m_PageScroll2id"> Features</a>
</div>