<section id="category-menu" class="">
			<div class="cat-menu">
			<a data-id="cat-menu" class="cat-menu-btn desktop"><h3>Shop By Category</h3></a>
			<ul id="cat-menuP" class="category-menup smartphones">
				<li><a href="#"><span></span>Phones &amp; Accessories</a></li>
				<li><a href="#"><span></span>Computer &amp; Accessories</a></li>
				<li><a href="#"><span></span>Consumer Electronics</a></li>
				<li><a href="#"><span></span>Games &amp; Accessories</a></li>
				<li><a href="#"><span></span>Home &amp; Office Supplies</a></li>
			</ul>
			<a class="cat-menu-btn smartphones" data-id="cat-menu"><h3>View All Categories</h3> <span><i class="fa fa-angle-right"></i></span></a>
			<ul id="cat-menu" class="category-menu desktop tablet">
				<li><a href="#">Clearance Sale</a></li>
				<li><a href="#">Phones &amp; Accessories</a></li>
				<li><a href="#">Computer &amp; Accessories</a></li>
				<li><a href="#">Consumer Electronics</a></li>
				<li><a href="#">Games &amp; Accessories</a></li>
				<li><a href="#">Home &amp; Office Supplies</a></li>
				<li><a href="#">Watches, Perfumes &amp; Gifts</a></li>
				<li><a href="#">Health, Beauty &amp; Sports</a></li>
				<li><a href="#">Fashion, Jewelry &amp; Accessories</a></li>
				<li><a href="#">Bags, Shoes &amp; Wallets</a></li> 
			</ul>
			</div>
		</section>
      
 