<?php
$getProductCollectionLatest = $this->getProductCollectionUpcomingPro();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$getProductCollectionLatest->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no categories matching'); ?></p>
<?php else: ?>      
    <?php foreach ($getProductCollectionLatest as $Latest): ?>
        <div>
            <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $Latest->getProductUrl() ?>">
                    <?php if (date("Y-m-d") >= substr($Latest->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($Latest->getNewsToDate(), 0, 10)) {
                        ?>
                        <span class="new">new</span>
        <?php } ?>

                    <div class="img-box"><div class="abs_center"><a href="<?php echo $Latest->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" class="product-image">
        <?php $_imgSize = 210; ?>
                                <img id="product-collection-image-<?php echo $Latest->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($Latest, 'small_image')->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" />
                            </a></div></div>
                    <div class="bottom-area">
                        <h4><?php echo $_helper->productAttribute($Latest, $Latest->getName(), 'name') ?></h4> 
                        <div class="price"><?php echo number_format($Latest->getPrice(), '1', '.', ','); ?><i>AED</i></div>
                    </div>
                </a>
            </div>
        </div>
    <?php endforeach ?>
<?php endif ?>