<?php
$category = Mage::registry('current_category')->getId();
$category_new = Mage::registry('current_category');
$category_new->url_key;
?>
<div class="margin1">
    <div class="slider">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($category_new->url_key)->toHtml(); ?>
    </div>
</div>
<section id="shopbybrand">
    <div class="sectiontitle">
        <h2><span>Shop by brand</span></h2>
    </div>
    <ul class="brands clearfix">
        <?php
        $_productCollectionbrand = $this->getLoadedProductCollectionbrand($category);
        $_helper = $this->helper('catalog/output');
        if (!$_productCollectionbrand->count()):
            ?>
            <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
        <?php else: ?>
            <?php foreach ($_productCollectionbrand as $_brand): ?>
                <?php $image = 'images/' . $_brand->thumbnail_image; ?>
                <li><div class="img-box"><div class="abs_center"><a href="<?php echo Mage::getBaseUrl().$_brand->url_key?>"><?php echo $_brand->name ?></a></div></div></li>
            <?php endforeach ?>
<?php endif; ?>
    </ul>
</section>
<section id="deals">
    <?php
    $_productCollection = $this->getLoadedProductCollection($category);
    $_helper = $this->helper('catalog/output');
    $count = 1;
    $toDate = date('Y-m-d');
    ?>
    <?php if ($_productCollection->count()): ?>
    <div class="sectiontitle">
        <h2><span>TODAY'S DEALS</span></h2>
        <h4>Deals End in  <span id="countbox_<?php echo $count; ?>"></span></h4>
    </div>
        <div class="columnslider" id="sectionDeals" data-items="3">
                    <?php foreach ($_productCollection as $_product): ?>
                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
                        <?php
                        $special = $_product->getSpecialPrice();
                        $actual = $_product->getPrice();
                        $percent = ($special / $actual) * 100;
                        $percentFinal = 100 - $percent;
                        ?>
                        <span class="discount"><?php echo number_format($percentFinal, '1', '.', ',') ?>%</span>
                        <div class="img-box"><div class="abs_center"><!-- <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"> -->
        <?php $_imgSize = 210; ?>
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                <!-- </a> --></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedSpecialPrice = Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?> <span class="not-now"> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($_product->getPrice(),true,false); ?> </span></div>
                        </div>
                    </a></div>
        <?php endforeach ?>
        </div>
        <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/sale?id=$category" ?>">View All Products</a></div>
<?php endif; ?>
    <script type="text/javascript">
        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
        start_date = Date.parse(start);
        var dnow<?php echo $count; ?> = new Date(start_date);
        if (CountStepper > 0)
            ddiff = new Date((dnow<?php echo $count; ?>) - (dthen<?php echo $count; ?>));
        else
            ddiff = new Date((dthen<?php echo $count; ?>) - (dnow<?php echo $count; ?>));
        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf() / 1000);
        var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
        CountBack(gsecs<?php echo $count; ?>, "countbox_" + timer, timer);
        timer++;
    </script>
<?php $count = $count + 1; ?>
</section>
<?php $_productCollectionseller = $this->getLoadedProductCollectionseller($category); ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getProductCollectionLatest($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getProductCollectionLatest($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="latestproducts" class="desktop">
    <div class="sectiontitle">
        <h2><span>Latest Products</span></h2>
            
            <?php $_helper = $this->helper('catalog/output');
            ?>
        <ul class="brandsmenu">
                <?php $_columnCount = $this->getColumnCount(); ?>
                <?php $i = 0;?>
                <?php $_product =  $_productCollectionseller->getFirstItem() ?>
                <li id="item<?php echo $_product->cat_id; ?>"><a onclick="getLatest(<?php echo $_product->cat_id ?>)" class="active"><?php echo $_product->cat_name; ?></a></li>
                 <?php $seller = $_product->cat_id; ?>
                <?php foreach ($_productCollectionseller as $_seller): ?>
                    <?php //$seller = $_seller->cat_id; ?>
                 <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li id="item<?php echo $_seller->cat_id; ?>"><a onclick="getLatest(<?php echo $_seller->cat_id ?>)"><?php echo $_seller->cat_name; ?></a></li>
                <?php break; ?>
                <?php endif ?>
                <?php $i++; ?>
            <?php endforeach ?>
        
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="latestproduct">

        <?php 
        //echo $seller; 
        $getProductCollectionLatest = $this->getProductCollectionLatest($seller);
        $_helper = $this->helper('catalog/output');
        ?>
        <?php if ($getProductCollectionLatest->count()) : ?>  
        <?php foreach ($getProductCollectionLatest as $Latest): ?>
                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $Latest->getProductUrl() ?>">
                                    <?php if (date("Y-m-d") >= substr($Latest->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($Latest->getNewsToDate(), 0, 10)) {
                                        ?>
                            <span class="new">new</span>
        <?php } ?> 

                        <div class="img-box"><div class="abs_center"><a href="<?php echo $Latest->getProductUrl() ?>"  class="product-image">
        <?php $_imgSize = 210; ?>
                                    <img id="product-collection-image-<?php echo $Latest->getId(); ?>"
                                         src="<?php echo $this->helper('catalog/image')->init($Latest, 'small_image')->resize($_imgSize); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" />
                                </a></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($Latest, $Latest->getName(), 'name') ?></h4> 
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?></div>
                        </div>
                    </a>
                </div>
    <?php endforeach ?>
<?php endif ?>
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/latest?id=$category" ?>">View All Products</a></div>
</section>
<?php endif ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getLoadedProductCollectionpro($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getLoadedProductCollectionpro($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="bestsellings" class="desktop">
    <div class="sectiontitle">
        <h2><span>Best Sellings</span></h2>
        <ul class="brandsmenu">
            <?php $_product =  $_productCollectionseller->getFirstItem() ?>
                <li id="item<?php echo $_product->cat_id; ?>"><a onclick="getBestseller(<?php echo $_product->cat_id ?>)" ><?php echo $_product->cat_name; ?></a></li>
            <?php foreach ($_productCollectionseller as $_seller): ?>

                <?php $seller = $_seller->cat_id; ?>
                <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li><a onclick="getBestseller(<?php echo $_seller->cat_id; ?>)" class = "active"><?php echo $_seller->cat_name; ?></a></li>
                    <?php break; ?>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="bestsellers">
<?php $getProductCollection = $this->getLoadedProductCollectionpro($seller);
$_helper = $this->helper('catalog/output');
?>
    <?php if ($getProductCollection->count()): ?>     
    <?php foreach ($getProductCollection as $Latest): ?>

                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $Latest->getProductUrl() ?>">
        <?php if (date("Y-m-d") >= substr($Latest->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($Latest->getNewsToDate(), 0, 10)) {
            ?>
                            <span class="new">new</span>
        <?php } ?>

                        <div class="img-box"><div class="abs_center"><a href="<?php echo $Latest->getProductUrl() ?>"  class="product-image">
        <?php $_imgSize = 210; ?>
                                    <img id="product-collection-image-<?php echo $Latest->getId(); ?>"
                                         src="<?php echo $this->helper('catalog/image')->init($Latest, 'small_image')->resize($_imgSize); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" />
                               <!-- </a>--></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($Latest, $Latest->getName(), 'name') ?></h4> 
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?></div>
                        </div>
                    </a>
                </div>
        <?php endforeach ?>
    <?php endif ?>
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/seller?id=$category" ?>">View All Products</a></div>
</section>
<?php endif ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getProductCollectionUpcoming($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getProductCollectionUpcoming($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="upcommingproducts" class="desktop">
            <?php
            ?>
    <div class="sectiontitle">
        <h2><span>Upcomming Products</span></h2>
        <ul class="brandsmenu">
    <?php $_product =  $_productCollectionseller->getFirstItem() ?>
    <li id="item<?php echo $_product->cat_id; ?>"><a onclick="getUpcoming(<?php echo $_product->cat_id ?>)"><?php echo $_product->cat_name; ?></a></li>
    <?php foreach ($_productCollectionseller as $_seller): ?>
                <?php $seller = $_seller->cat_id; ?>
                <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li><a onclick="getUpcoming(<?php echo $_seller->cat_id; ?>)" class = "active"><?php echo $_seller->cat_name; ?></a></li>
                <?php break; ?>
                <?php endif ?>
            <?php endforeach ?>
       
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="upcoming">
        <?php $getUpcomingProduct = $this->getProductCollectionUpcoming($seller);
        $_helper = $this->helper('catalog/output');
        ?>            
        <?php if ($getUpcomingProduct->count()): ?>     
            <?php foreach ($getUpcomingProduct as $Latest): ?>
        <?php $upcomingproduct = $Latest->getAttributeText('upcomingproduct') ?>

                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $Latest->getProductUrl() ?>">
        <?php if (date("Y-m-d") >= substr($Latest->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($Latest->getNewsToDate(), 0, 10)) {
            ?>
                            <span class="new">new</span>
        <?php } ?>

                        <div class="img-box"><div class="abs_center"><a href="<?php echo $Latest->getProductUrl() ?>"  class="product-image">
        <?php $_imgSize = 210; ?>
                                    <img id="product-collection-image-<?php echo $Latest->getId(); ?>"
                                         src="<?php echo $this->helper('catalog/image')->init($Latest, 'small_image')->resize($_imgSize); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" />
                                </a></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($Latest, $Latest->getName(), 'name') ?></h4> 
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?></div>
                        </div>
                    </a>
                </div>

    <?php endforeach ?>
<?php endif ?>
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/upcoming?id=$category" ?>">View All Products</a></div>
</section>
 <?php endif ?>
<script>
    jQuery(document).ready(function () {
        jQuery("#itemfirst a").addClass("active");

    });
    function getLatest(cat_id) {
        
        jQuery("#item" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxlatestproduct/',
            type: 'POST',
            data: {action: 'getProductCollectionLatestpro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#latestproduct').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#latestproduct').html(data);
                reinitOwlOnSelector('#latestproduct',3);
            }
        });
    }

    function getBestseller(cat_id) {
        jQuery("#item" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestsellerproduct/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionsellers', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#bestsellers').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestsellers').html(data);
                reinitOwlOnSelector('#bestsellers',3);
            }
        });
    }

    function getUpcoming(cat_id) {
    
        jQuery("#item" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxupcoming/',
            type: 'POST',
            data: {action: 'getProductCollectionUpcomingPro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#upcoming').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#upcoming').html(data);
                reinitOwlOnSelector('#upcoming',3);
            }
        });
    }
</script>