<?php
$category = Mage::registry('current_category')->getId();
$category_new = Mage::registry('current_category');
$category_new->url_key;
?>
<div class="margin1">
    <div class="slider">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($category_new->url_key)->toHtml(); ?>
    </div>
</div>
<section id="shopbybrand">
    <div class="sectiontitle">
        <h2><span>Shop by brand</span></h2>
    </div>
    <ul class="brands clearfix">
        <?php
       $_productCollectionbrand = $this->getproductbrands($category);
       $_helper = $this->helper('catalog/output');
        foreach ($_productCollectionbrand as $brand):
                        ?>
            <?php $a[]= $brand->brand_urlkey; ?>
            <?php $b[] = $brand->brand_name; ?>
            <?php print_r($b) ?>
        <?php endforeach ?>
       <?php/*  $optionid = array_unique($a); ?>
        <?php $brandname = array_unique($b); ?>
        <?php $max = sizeof($brandname); ?>
        <?php $i = 0; ?>
        <?php if ($max >= 5): ?>
        <?php while($i < 5){?>
        <?php if($optionid[$i] != ""){ ?>  
        <li><div class="img-box"><div class="abs_center"><a href="<?php echo $optionid[$i];?>"><?php echo $brandname[$i];?></a></div></div></li>
        <?php $i = $i + 1; ?>
          <?php } ?>
        <?php } ?>  
        <?php elseif($max < 5): ?> 
        
        <?php while($i < $max){?>
           <?php if($optionid[$i] != ""){ ?>  
           <li><div class="img-box"><div class="abs_center"><a href="<?php echo $optionid[$i];?>"><?php echo $brandname[$i];?></a></div></div></li>
           <?php $i = $i + 1;?>
            <?php } ?>  
        <?php } ?>
        <?php endif */?>
    </ul>
</section>
<section id="deals">
    <?php
    $_productCollection = $this->getLoadedProductCollection($category);
    $_helper = $this->helper('catalog/output');
    $count = 1;
    $toDate = date('Y-m-d');
    ?>
    <?php if ($_productCollection->count()): ?>
    <div class="sectiontitle">
        <h2><span>TODAY'S DEALS</span></h2>
        <h4>Deals End in  <span id="countbox_<?php echo $count; ?>"></span></h4>
    </div>
        <div class="columnslider" id="sectionDeals" data-items="3">
                    <?php foreach ($_productCollection as $_product): ?>
                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $_product->getProductUrl() ?>">
                        <?php
                        $special = $_product->getSpecialPrice();
                        $actual = $_product->getPrice();
                        $percent = ($special / $actual) * 100;
                        $percentFinal = 100 - $percent;
                        ?>
                        <span class="discount"><?php echo number_format($percentFinal, '0', '.', ',') ?>%</span>
                        <div class="img-box"><div class="abs_center"><!-- <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"> -->
        <?php $_imgSize = 210; ?>
                                <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                <!-- </a> --></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
                            <?php 
							  $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                              $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                             $today =  time();
							?>
                           <?php   $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); ?>
                            <?php if($specialprice and ($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate))) {?>
                            
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedSpecialPrice = Mage::helper('core')->currency($_product->getFinalPrice(),true,false); ?> <span class="not-now"> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($_product->getPrice(),true,false); ?> </span></div>
                            <?php } else {  ?>
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($_product->getPrice(),true,false); ?></div>
                            <?php } ?>
                        </div>
                    </a>
                    <div class="actions">
                        <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                    <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                        <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                    </div>
                    </div>
        <?php endforeach ?>
        </div>
        <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/sale?id=$category" ?>">View All Products</a></div>
<?php endif; ?>
    <script type="text/javascript">
        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
        start_date = Date.parse(start);
        var dnow<?php echo $count; ?> = new Date(start_date);
        if (CountStepper > 0)
            ddiff = new Date((dnow<?php echo $count; ?>) - (dthen<?php echo $count; ?>));
        else
            ddiff = new Date((dthen<?php echo $count; ?>) - (dnow<?php echo $count; ?>));
        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf() / 1000);
        var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
        CountBack(gsecs<?php echo $count; ?>, "countbox_" + timer, timer);
        timer++;
    </script>
<?php $count = $count + 1; ?>
</section>
<?php $_productCollectionseller = $this->getLoadedProductCollectionseller($category); ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getProductCollectionLatest($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getProductCollectionLatest($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="latestproducts" class="desktop">
    <div class="sectiontitle">
        <h2><span>Latest Products</span></h2>
            <?php $_helper = $this->helper('catalog/output');
            ?>
        <ul class="brandsmenu" id="brandsLatestProducts">
                <?php $_columnCount = $this->getColumnCount(); ?>
                <?php $i = 0;?>
                <?php $_product =  $_productCollectionseller->getFirstItem() ?>
                <li id="item<?php echo $_product->cat_id; ?>" ><a onclick="getLatest(<?php echo $_product->cat_id ?>)" class="active" ><?php echo $_product->cat_name; ?></a></li>
                 <?php $seller = $_product->cat_id; ?>
                <?php foreach ($_productCollectionseller as $_seller): ?>
                    <?php //$seller = $_seller->cat_id; ?>
                 <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li id="item<?php echo $_seller->cat_id; ?>"><a onclick="getLatest(<?php echo $_seller->cat_id ?>)"><?php echo $_seller->cat_name; ?></a></li>
                <?php break; ?>
                <?php endif ?>
                <?php $i++; ?>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="latestproduct">

        <?php 
        //echo $seller; 
        $getProductCollectionLatest = $this->getProductCollectionLatest($seller);
        $_helper = $this->helper('catalog/output');
        ?>
        <?php if ($getProductCollectionLatest->count()) : ?>  
        <?php foreach ($getProductCollectionLatest as $Latest): ?>
                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $Latest->getProductUrl() ?>">
                                    <?php if (date("Y-m-d") >= substr($Latest->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($Latest->getNewsToDate(), 0, 10)) {
                                        ?>
                            <span class="new">new</span>
        <?php } ?> 

                        <div class="img-box"><div class="abs_center"><a href="<?php echo $Latest->getProductUrl() ?>"  class="product-image">
        <?php $_imgSize = 210; ?>
                                    <img id="product-collection-image-<?php echo $Latest->getId(); ?>"
                                         src="<?php echo $this->helper('catalog/image')->init($Latest, 'small_image')->resize($_imgSize); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" />
                                </a></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($Latest, $Latest->getName(), 'name') ?></h4> 
                            <?php 
							  $specialPriceFromDate = Mage::getModel('catalog/product')->load($Latest->getId())->getSpecialFromDate();
                              $specialPriceToDate = Mage::getModel('catalog/product')->load($Latest->getId())->getSpecialToDate();
                             $today =  time();
							?>
                           <?php   $specialprice = Mage::getModel('catalog/product')->load($Latest->getId())->getSpecialPrice(); ?>
                            <?php if($specialprice and ($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate))) {?>
                            
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedSpecialPrice = Mage::helper('core')->currency($Latest->getFinalPrice(),true,false); ?> <span class="not-now"> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?> </span></div>
                            <?php } else {  ?>
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?></div>
                            <?php } ?>
                        </div>
                    </a>
                    <div class="actions">
                        <?php if(!$Latest->canConfigure() && $Latest->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($Latest) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($Latest->getStockItem() && $Latest->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $Latest->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <!-- <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul> -->
                    </div>
                </div>
    <?php endforeach ?>
<?php endif ?>
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/latest?id=$category" ?>">View All Products</a></div>
</section>
<?php endif ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getLoadedProductCollectionpro($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getLoadedProductCollectionpro($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="bestsellings" class="desktop">
    <div class="sectiontitle">
        <h2><span>Best Sellings</span></h2>
        <ul class="brandsmenu" id="brandsBestSellings">
            <?php $_product =  $_productCollectionseller->getFirstItem() ?>
                <li id="items<?php echo $_product->cat_id; ?>"><a onclick="getBestseller(<?php echo $_product->cat_id ?>)" ><?php echo $_product->cat_name; ?></a></li>
            <?php foreach ($_productCollectionseller as $_seller): ?>

                <?php $seller = $_seller->cat_id; ?>
                <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li id="items<?php echo $_product->cat_id; ?>"><a onclick="getBestseller(<?php echo $_seller->cat_id; ?>)" class ="active" ><?php echo $_seller->cat_name; ?></a></li>
                    <?php break; ?>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="bestsellers">
<?php $getProductCollection = $this->getLoadedProductCollectionpro($seller);
$_helper = $this->helper('catalog/output');
?>
    <?php if ($getProductCollection->count()): ?>     
    <?php foreach ($getProductCollection as $Latest): ?>

                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $Latest->getProductUrl() ?>">
        <?php if (date("Y-m-d") >= substr($Latest->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($Latest->getNewsToDate(), 0, 10)) {
            ?>
                            <span class="new">new</span>
        <?php } ?>

                        <div class="img-box"><div class="abs_center"><a href="<?php echo $Latest->getProductUrl() ?>"  class="product-image">
        <?php $_imgSize = 210; ?>
        <img id="product-collection-image-<?php echo $Latest->getId(); ?>" src="<?php echo $this->helper('catalog/image')->init($Latest, 'small_image')->resize($_imgSize); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" /> <!-- </a>--></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($Latest, $Latest->getName(), 'name') ?></h4> 
                            <?php 
							  $specialPriceFromDate = Mage::getModel('catalog/product')->load($Latest->getId())->getSpecialFromDate();
                              $specialPriceToDate = Mage::getModel('catalog/product')->load($Latest->getId())->getSpecialToDate();
                             $today =  time();
							?>
                           <?php   $specialprice = Mage::getModel('catalog/product')->load($Latest->getId())->getSpecialPrice(); ?>
                            <?php if($specialprice and ($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate))) {?>
                            
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedSpecialPrice = Mage::helper('core')->currency($Latest->getFinalPrice(),true,false); ?> <span class="not-now"> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?> </span></div>
                            <?php } else {  ?>
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?></div>
                            <?php } ?>
                        </div>
                    </a>
                   <div class="actions">
                        <?php if(!$Latest->canConfigure() &&$Latest->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($Latest) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($Latest->getStockItem() && $Latest->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $Latest->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <!-- <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul> -->
                    </div>
                </div>
        <?php endforeach ?>
    <?php endif ?>
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/seller?id=$category" ?>">View All Products</a></div>
</section>
<?php endif ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getProductCollectionUpcoming($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getProductCollectionUpcoming($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="upcommingproducts" class="desktop">
            <?php
            ?>
    <div class="sectiontitle">
        <h2><span>Upcomming Products</span></h2>
        <ul class="brandsmenu" id="brandsUpComing">
    <?php $_product =  $_productCollectionseller->getFirstItem() ?>
    <li id="item1<?php echo $_product->cat_id; ?>"><a onclick="getUpcoming(<?php echo $_product->cat_id ?>)"><?php echo $_product->cat_name; ?></a></li>
    <?php foreach ($_productCollectionseller as $_seller): ?>
                <?php $seller = $_seller->cat_id; ?>
                <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li id="item1<?php echo $_product->cat_id; ?>"><a onclick="getUpcoming(<?php echo $_seller->cat_id; ?>)" class ="active"><?php echo $_seller->cat_name; ?></a></li>
                <?php break; ?>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="upcoming">
        <?php $getUpcomingProduct = $this->getProductCollectionUpcoming($seller);
        $_helper = $this->helper('catalog/output');
        ?>            
        <?php if ($getUpcomingProduct->count()): ?>     
            <?php foreach ($getUpcomingProduct as $Latest): ?>
        <?php $upcomingproduct = $Latest->getAttributeText('upcomingproduct') ?>

                <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>"><a href="<?php echo $Latest->getProductUrl() ?>">
        <?php if (date("Y-m-d") >= substr($Latest->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($Latest->getNewsToDate(), 0, 10)) {
            ?>
                            <span class="new">new</span>
        <?php } ?>

                        <div class="img-box"><div class="abs_center"><a href="<?php echo $Latest->getProductUrl() ?>"  class="product-image">
        <?php $_imgSize = 210; ?>
                                    <img id="product-collection-image-<?php echo $Latest->getId(); ?>"
                                         src="<?php echo $this->helper('catalog/image')->init($Latest, 'small_image')->resize($_imgSize); ?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($Latest, 'small_image'), null, true) ?>" />
                                </a></div></div>
                        <div class="bottom-area">
                            <h4><?php echo $_helper->productAttribute($Latest, $Latest->getName(), 'name') ?></h4> 
                            <div class="price"><?php echo $this->getChildHtml('bundle_prices') ?> <?php echo $_formattedActualPrice = Mage::helper('core')->currency($Latest->getPrice(),true,false); ?></div>
                        </div>
                    </a>
                   <div class="actions">
                        <?php if(!$Latest->canConfigure() && $Latest->isSaleable()): ?>
                            <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($Latest) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php elseif($Latest->getStockItem() && $Latest->getStockItem()->getIsInStock()): ?>
                            <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $Latest->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <!-- <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul> -->
                    </div>
                </div>
    <?php endforeach ?>
<?php endif ?>
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl() . "extension/category/upcoming?id=$category" ?>">View All Products</a></div>
</section>
 <?php endif ?>
<script>
    jQuery(document).ready(function () {
        jQuery("#itemfirst a").addClass("active");

    });
    function getLatest(cat_id) {
        jQuery('#brandsLatestProducts li a').removeClass("active");
        jQuery("#item" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxlatestproduct/',
            type: 'POST',
            data: {action: 'getProductCollectionLatestpro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#latestproduct').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#latestproduct').html(data);
                reinitOwlOnSelector('#latestproduct',3);
            }
        });
    }

    function getBestseller(cat_id) {
        jQuery('#brandsBestSellings li a').removeClass("active");
        jQuery("#item" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestsellerproduct/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionsellers', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#bestsellers').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestsellers').html(data);
                reinitOwlOnSelector('#bestsellers',3);
            }
        });
    }

    function getUpcoming(cat_id) {
        jQuery('#brandsUpComing li a').removeClass("active");
        jQuery("#item1" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxupcoming/',
            type: 'POST',
            data: {action: 'getProductCollectionUpcomingPro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#upcoming').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#upcoming').html(data);
                reinitOwlOnSelector('#upcoming',3);
            }
        });
    }
</script>