<div class="col-sm-12 col-md-9">
		<div class="margin1">
			<div class="slider">
			<div><img src="images/slide3.jpg" alt=""></div>
			<div><img src="images/slide3.jpg" alt=""></div>
			</div>
		</div>
		<section id="shopbybrand">
			<div class="sectiontitle">
				<h2><span>Shop by brand</span></h2>
			</div>
			<ul class="brands clearfix">
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-oneplus.jpg" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-lenovo.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-nokia.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-htc.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-sony.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-lg.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-dcogee.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-inew.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-motorola.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-aiya.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-amoi.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-meizl.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-koobee.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-cubot.png" alt=""></a></div></div></li>
				<li><div class="img-box"><div class="abs_center"><a href="#"><img src="images/logo-blackberry.png" alt=""></a></div></div></li>
			</ul>
		</section>
		<section id="deals">
			<div class="sectiontitle">
				<h2><span>TODAY'S DEALS</span></h2>
				<h4>Deals End in  <span>00:00:00</span></h4>
			</div>
			<div class="columnslider" id="sectionDeals" data-items="3">
				<div class="col-box"><a href="#">
					<span class="discount">43%</span>
					<div class="img-box"><div class="abs_center"><img src="images/headphone1.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Beats Solo 2 Wireless</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">20%</span>
					<div class="img-box"><div class="abs_center"><img src="images/ipad.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>iPAD Air (Retina)</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">15%</span>
					<div class="img-box"><div class="abs_center"><img src="images/macbookair.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Mackbook Air (Retina)</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">08%</span>
					<div class="img-box"><div class="abs_center"><img src="images/beatssolo2.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Beats Solo 2 Wireless</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
				<div class="col-box"><a href="#">
					<span class="discount">15%</span>
					<div class="img-box"><div class="abs_center"><img src="images/headphone1.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Beats Solo 2 Wireless</h4>
					<div class="price">20<i>AED</i> <span class="not-now">34<i>AED</i></span></div>
					</div>
					</a>
				</div>
			</div>
			<div class="clearfix viewmore" align="right"><a href="#">View All Products</a></div>
		</section>
		<section id="latestproducts" class="desktop">
			<div class="sectiontitle">
				<h2><span>Latest Products</span></h2>
				<ul class="brandsmenu">
					<li><a href="#">Tablets</a></li>
					<li><a href="#" class="active">Mobiles</a></li>
				</ul>
			</div>
					<div class="columnslider" data-items="3">
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/samsung-galaxy-s6-tab.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Samsung Galaxy Tab 4 - 7″</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<span class="new">new</span>
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/hot-touch-slim-armor.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Hot Touch Slim Armor</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/pu-wallet-leather.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>PU Wallet Leather</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
			</div>
		<div class="clearfix viewmore" align="right"><a href="#">View All Products</a></div>
		</section>
		<section id="bestsellings" class="desktop">
			<div class="sectiontitle">
				<h2><span>Best Sellings</span></h2>
				<ul class="brandsmenu">
					<li><a href="#" class="active">Tablets</a></li>
					<li><a href="#">Mobiles</a></li>
				</ul>
			</div>
					<div class="columnslider" data-items="3">
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/samsung-galaxy-s6-tab.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Samsung Galaxy Tab 4 - 7″</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<span class="new">new</span>
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/hot-touch-slim-armor.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Hot Touch Slim Armor</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/pu-wallet-leather.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>PU Wallet Leather</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
			</div>
		<div class="clearfix viewmore" align="right"><a href="#">View All Products</a></div>
		</section>
		<section id="upcommingproducts" class="desktop">
			<div class="sectiontitle">
				<h2><span>Upcomming Products</span></h2>
				<ul class="brandsmenu">
					<li><a href="#">Tablets</a></li>
					<li><a href="#" class="active">Mobiles</a></li>
				</ul>
			</div>
					<div class="columnslider" data-items="3">
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/samsung-galaxy-s6-tab.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Samsung Galaxy Tab 4 - 7″</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<span class="new">new</span>
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/hot-touch-slim-armor.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Hot Touch Slim Armor</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/pu-wallet-leather.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>PU Wallet Leather</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
				<div class="col-box"><a href="#">
					<div class="img-box"><div class="abs_center"><img src="images/kindle-paper-white.jpg" alt=""></div></div>
					<div class="bottom-area">
					<h4>Kindle Paperwhite 6</h4>
					<div class="price">20<i>AED</i></div>
					</div></a>
				</div>
			</div>
		<div class="clearfix viewmore" align="right"><a href="#">View All Products</a></div>
		</section>
		</div>