<?php
$category = Mage::registry('current_category')->getId();
$category_new = Mage::registry('current_category');
$category_new->url_key;
?>
<input type="hidden" id="cats" name="cats" value ="<?php echo $category ?>"/>
<div class="margin1">
    <div class="slider">
         <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($category_new->url_key)->toHtml(); ?>
    </div>
</div>
<section id="shopbybrand">
    <div class="sectiontitle">
        <h2><span>Shop by brand</span></h2>
    </div>
    <ul class="brands clearfix">
        <?php
       $_productCollectionbrand = $this->getproductbrands($category);
       $_helper = $this->helper('catalog/output');
        foreach ($_productCollectionbrand as $brand):
                        ?>
                <li><div class="img-box"><div class="abs_center"><a href="<?php echo $brand->brand_urlkey;?>"><?php echo $brand->brand_name;?></a></div></div></li>
            <?php //$a[]= $brand->brand_urlkey; ?>
            <?php //$b[] = $brand->brand_name; ?>
            <?php //print_r($b) ?>
        <?php endforeach ?>
       <?php /*  $optionid = array_unique($a); ?>
        <?php $brandname = array_unique($b); ?>
        <?php $max = sizeof($brandname); ?>
        <?php $i = 0; ?>
        <?php if ($max >= 5): ?>
        <?php while($i < 5){?>
        <?php if($optionid[$i] != ""){ ?>  
        <li><div class="img-box"><div class="abs_center"><a href="<?php echo $optionid[$i];?>"><?php echo $brandname[$i];?></a></div></div></li>
        <?php $i = $i + 1; ?>
          <?php } ?>
        <?php } ?>  
        <?php elseif($max < 5): ?> 
        
        <?php while($i < $max){?>
           <?php if($optionid[$i] != ""){ ?>  
           <li><div class="img-box"><div class="abs_center"><a href="<?php echo $optionid[$i];?>"><?php echo $brandname[$i];?></a></div></div></li>
           <?php $i = $i + 1;?>
            <?php } ?>  
        <?php } ?>
        <?php endif */ ?>
    </ul>
</section>
<section id="deals">
    <?php
    $_productCollection = $this->getLoadedProductCollection($category);
    $_helper = $this->helper('catalog/output');
    $count = 1;
    $toDate = date('Y-m-d');
    ?>
    <?php if ($_productCollection->count()): ?>
    <div class="sectiontitle">
        <h2><span>TODAY'S DEALS</span></h2>
        <h4>Deals End in  <span id="countbox_<?php echo $count; ?>"></span></h4>
    </div>
        <div class="columnslider" id="sectionDeals" data-items="3">
          <!--- load through ajax -->          
        </div>
        <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).Mage::helper('extension')->getCustomUrl('todaysdeals')?>?id=<?php echo $category ?>">View All Products</a></div>
<?php endif; ?>
    <script type="text/javascript">
        var dthen<?php echo $count; ?> = new Date("<?php echo Date("m/d/y", strtotime($toDate)) . ' 11:59:00 PM'; ?>");
        start = "<?php echo Date("m/d/y h:i:s A", strtotime(Mage_Core_Model_Locale::date(null, null, "en_US", true))); ?>";
        start_date = Date.parse(start);
        var dnow<?php echo $count; ?> = new Date(start_date);
        if (CountStepper > 0)
            ddiff = new Date((dnow<?php echo $count; ?>) - (dthen<?php echo $count; ?>));
        else
            ddiff = new Date((dthen<?php echo $count; ?>) - (dnow<?php echo $count; ?>));
        gsecs<?php echo $count; ?> = Math.floor(ddiff.valueOf() / 1000);
        var iid<?php echo $count; ?> = "countbox_<?php echo $count; ?>";
        CountBack(gsecs<?php echo $count; ?>, "countbox_" + timer, timer);
        timer++;
    </script>
<?php $count = $count + 1; ?>
</section>
<?php $_productCollectionseller = $this->getLoadedProductCollectionseller($category); ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getProductCollectionLatest($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getProductCollectionLatest($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="latestproducts">
    <div class="sectiontitle">
        <h2><span>Latest Products</span></h2>
            <?php $_helper = $this->helper('catalog/output');
            ?>
        <ul class="brandsmenu" id="brandsLatestProducts">
                <?php $_columnCount = $this->getColumnCount(); ?>
                <?php $i = 0;?>
                <?php $_product =  $_productCollectionseller->getFirstItem() ?>
                <li id="item<?php echo $_product->cat_id; ?>" ><a onclick="getLatest(<?php echo $_product->cat_id ?>)" class="active" ><?php echo $_product->cat_name; ?></a></li>
                 <?php $seller = $_product->cat_id; ?>
                <?php foreach ($_productCollectionseller as $_seller): ?>
                    <?php //$seller = $_seller->cat_id; ?>
                 <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li id="item<?php echo $_seller->cat_id; ?>"><a onclick="getLatest(<?php echo $_seller->cat_id ?>)"><?php echo $_seller->cat_name; ?></a></li>
                <?php break; ?>
                <?php endif ?>
                <?php $i++; ?>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="latestproduct">
        <!--- load through ajax -->
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).Mage::helper('extension')->getCustomUrl('latestproduct')?>?id=<?php echo $category ?>">View All Products</a></div>
</section>
<?php endif ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getLoadedProductCollectionpro($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getLoadedProductCollectionpro($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="bestsellings">
    <div class="sectiontitle">
        <h2><span>Best Sellings</span></h2>
        <ul class="brandsmenu" id="brandsBestSellings">
            <?php $_product =  $_productCollectionseller->getFirstItem() ?>
                <li id="items<?php echo $_product->cat_id; ?>"><a onclick="getBestseller(<?php echo $_product->cat_id ?>)" ><?php echo $_product->cat_name; ?></a></li>
            <?php foreach ($_productCollectionseller as $_seller): ?>

                <?php $seller = $_seller->cat_id; ?>
                <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li id="items<?php echo $_seller->cat_id; ?>"><a onclick="getBestseller(<?php echo $_seller->cat_id; ?>)" class ="active" ><?php echo $_seller->cat_name; ?></a></li>
                    <?php break; ?>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="bestsellers">
        <!--- load through ajax -->
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).Mage::helper('extension')->getCustomUrl('bestseller')?>?id=<?php echo $category ?>">View All Products</a></div>
</section>
<?php endif ?>
<?php $_product =  $_productCollectionseller->getFirstItem() ?>
<?php $seller = $_product->cat_id; ?>
<?php $getProductCollectionLatest = $this->getProductCollectionUpcoming($seller); ?>
<?php foreach ($_productCollectionseller as $_seller): ?>
            <?php $seller = $_seller->cat_id; ?>
            <?php break; ?>
<?php endforeach ?>
<?php $getProductCollectionLatests = $this->getProductCollectionUpcoming($seller); ?>
<?php if ($_productCollectionseller->count() && ($getProductCollectionLatests->count() || $getProductCollectionLatest->count()) ): ?>
<section id="upcommingproducts">
            <?php
            ?>
    <div class="sectiontitle">
        <h2><span>Upcomming Products</span></h2>
        <ul class="brandsmenu" id="brandsUpComing">
    <?php $_product =  $_productCollectionseller->getFirstItem() ?>
    <li id="item1<?php echo $_product->cat_id; ?>"><a onclick="getUpcoming(<?php echo $_product->cat_id ?>)"><?php echo $_product->cat_name; ?></a></li>
    <?php foreach ($_productCollectionseller as $_seller): ?>
                <?php $seller = $_seller->cat_id; ?>
                <?php if($_product->cat_id != $_seller->cat_id) :?>
                    <li id="item1<?php echo $_product->cat_id; ?>"><a onclick="getUpcoming(<?php echo $_seller->cat_id; ?>)" class ="active"><?php echo $_seller->cat_name; ?></a></li>
                <?php break; ?>
                <?php endif ?>
            <?php endforeach ?>
        </ul>
    </div>
    <div class="columnslider" data-items="3" id="upcoming">
    <!-- load through Ajax-->
    </div>
    <div class="clearfix viewmore" align="right"><a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).Mage::helper('extension')->getCustomUrl('upcoming')?>?id=<?php echo $category ?>">View All Products</a></div>
</section>
 <?php endif ?>
<script>
    jQuery(document).ready(function () {
        jQuery("#itemfirst a").addClass("active");
        var cat_id = document.getElementById("cats").value;
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/category/latestcategoryproductAjax/',
            type: 'POST',
            data: {action: 'getLoadedProductCollection', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#sectionDeals').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#sectionDeals').html(data);
                reinitOwlOnSelector('#sectionDeals',3);
            }
        });

        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxlatestproduct/',
            type: 'POST',
            data: {action: 'getProductCollectionLatestpro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#latestproduct').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#latestproduct').html(data);
                reinitOwlOnSelector('#latestproduct',3);
            }
        });

        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestsellerproduct/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionsellers', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#bestsellers').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestsellers').html(data);
                reinitOwlOnSelector('#bestsellers',3);
            }
        });

         jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxupcoming/',
            type: 'POST',
            data: {action: 'getProductCollectionUpcomingPro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#upcoming').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#upcoming').html(data);
                reinitOwlOnSelector('#upcoming',3);
            }
        });

    });
    function getLatest(cat_id) {
        jQuery('#brandsLatestProducts li a').removeClass("active");
        jQuery("#item" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxlatestproduct/',
            type: 'POST',
            data: {action: 'getProductCollectionLatestpro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#latestproduct').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#latestproduct').html(data);
                reinitOwlOnSelector('#latestproduct',3);
            }
        });
    }

    function getBestseller(cat_id) {
        jQuery('#brandsBestSellings li a').removeClass("active");
        jQuery("#items" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxbestsellerproduct/',
            type: 'POST',
            data: {action: 'getLoadedProductCollectionsellers', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#bestsellers').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#bestsellers').html(data);
                reinitOwlOnSelector('#bestsellers',3);
            }
        });
    }

    function getUpcoming(cat_id) {
        jQuery('#brandsUpComing li a').removeClass("active");
        jQuery("#item1" + cat_id + " a").addClass("active");
        jQuery.ajax({
            url: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB)?>index.php/extension/index/ajaxupcoming/',
            type: 'POST',
            data: {action: 'getProductCollectionUpcomingPro', cat_ids: cat_id},
            beforeSend: function () {
                jQuery('#upcoming').html("<div class='loader'><img src='<?php echo $this->getSkinUrl('images/ajax-loader2.gif') ?>' /></div>");
            },
            success: function (data) {
                jQuery('#upcoming').html(data);
                reinitOwlOnSelector('#upcoming',3);
            }
        });
    }
</script>
