<section class="__faq">
    <!--<h1>I Need Help With...</h1>-->
    <div class="row">
      <div class="col-sm-8"> 
        <!--
<form class="__faq__search">
<div class="form-group"><input class="form-control" type="text" placeholder="Your Search Here" /> <button type="submit"></button></div>
</form>
<span id="helpBlock" class="help-block">ex : Returns, Exchange, Damaged product</span>-->
        <h2>Please select what you want to contact us about:</h2>
        <div><!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation"  class="active"> <a data-toggle="tab" role="tab" aria-controls="order" href="#order">Order</a></li>
            <li role="presentation"> <a data-toggle="tab" role="tab" aria-controls="wallet" href="#wallet">Wallet</a></li>
            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="shopping" href="#shopping">Shopping</a></li>
            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="payment" href="#payment">Payment</a></li>
            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="shipping" href="#shipping">Shipping</a></li>
            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="refund" href="#refund">Refund</a></li>
            <li role="presentation"><a data-toggle="tab" role="tab" aria-controls="others" href="#others">Others</a></li>
          </ul>
          <!-- Tab panes -->
          <div class="tab-content">
            <div id="order" class="tab-pane active" role="tabpanel">
              <div id="accordion" class="panel-group" role="tablist">
                <div class="panel panel-default">
                  <div id="headingEight" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a role="button" href="#collapseEight" data-toggle="collapse" data-parent="#accordion"> 
                    How do I know my order has been confirmed? </a></h4>
                  </div>
                  <div id="collapseEight" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>Once your order has been logged and payment authorization has been received, the seller confirms receipt of the order and begins processing it.</p>
                      <p>You will receive an email containing the details of your order when the seller receives it and confirms the same. In this mail you will be provided with a unique Order ID, a listing of the item(s) you have ordered and the expected delivery time.</p>
                      <p>You will also be notified when the seller ships the item(s) to you. Shipping details will be provided with the respective tracking number(s).</p>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div id="headingOne" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a role="button" href="#collapseOne" data-toggle="collapse" data-parent="#accordion"> 
                    How do I check the current status of my orders? 
                    </a></h4>
                  </div>
                  <div id="collapseOne" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>Once your order has been logged and payment authorization has been received, the seller confirms receipt of the order and begins processing it.</p>
                      <p>You can review the status of your orders and other related information in the 'My Account' section in the My Account page, click on the 'My Orders' link to view the status of all your orders. To view the status of a specific order, click on the 'Order Number' link.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
            <div id="wallet" class="tab-pane" role="tabpanel">  
            <div class="__not__found">No Record Found</div>
            </div>
            
            <div id="shopping" class="tab-pane" role="tabpanel">
              <div id="accordion2" class="panel-group" role="tablist">
                <div class="panel panel-default">
                  <div id="headingTwo" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a class="collapsed" role="button" href="#collapseTwo" data-toggle="collapse" data-parent="#accordion2"> What is 'My Account'? How do I update my information? </a></h4>
                  </div>
                  <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>It is easy to update your Ecart.ae account and view your orders any time through 'My Account'. 'My Account' allows you complete control over your transactions on Ecart.ae Manage/edit your personal data like address, phone numbers, email ids Change your password Track the status of your orders</p>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div id="headingNine" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a class="collapsed" role="button" href="#collapseNine" data-toggle="collapse" data-parent="#accordion2"> How does the delivery process work? </a></h4>
                  </div>
                  <div id="collapseNine" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>eCart.ae has got his own logistic department to delivery all your goods on time.All electronic items are insured for theft and damages during transit.</p>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div id="headingThree" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a class="collapsed" role="button" href="#collapseThree" data-toggle="collapse" data-parent="#accordion2"> Can I order a product that is 'Out of Stock'? </a></h4>
                  </div>
                  <div id="collapseThree" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>Unfortunately, products listed as 'Out of Stock' are not available for sale. Please use the 'Notify Me' feature to be informed of the product's availability with sellers on Ecart.ae.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div id="payment" class="tab-pane" role="tabpanel">
              <div id="accordion3" class="panel-group" role="tablist">
                <div class="panel panel-default">
                  <div id="headingSix" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a class="collapsed" role="button" href="#collapseSix" data-toggle="collapse" data-parent="#accordion3"> How do I pay using a credit? </a></h4>
                  </div>
                  <div id="collapseSix" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>We accept payments made by credit/debit cards issued in India and 21 other countries. Credit cards
                        We accept payments made using Visa, MasterCard. To pay using your credit card at checkout, you will need your card number, expiry date, three-digit CVV number (found on the backside of your card). After entering these details, you will be redirected to the bank's page for entering the online 3D Secure password.</p>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div id="headingSeven" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a class="collapsed" role="button" href="#collapseSeven" data-toggle="collapse" data-parent="#accordion3"> Is it safe to use my credit on eCart.ae? </a></h4>
                  </div>
                  <div id="collapseSeven" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>Your online transaction on eCart.ae is secure with the highest levels of transaction security currently available on the Internet. eCart.ae uses 256-bit encryption technology to protect your card information while securely transmitting it to the respective banks for payment processing.
                        All credit card and debit card payments on eCart.ae are processed through secure and trusted payment gateways managed by leading banks. Banks now use the 3D Secure password service for online transactions, providing an additional layer of security through identity verification.</p>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div id="headingFour" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a class="collapsed" role="button" href="#collapseFour" data-toggle="collapse" data-parent="#accordion3"> How do I pay for a eCart.ae purchase?</a></h4>
                  </div>
                  <div id="collapseFour" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>eCart.ae offers you multiple payment methods. Whatever your online mode of payment, you can rest assured that Ecart.ae’s trusted payment gateway partners use secure encryption technology to keep your transaction details confidential at all times.
                        
                        eCart.ae also accepts payments made using Visa, MasterCard.</p>
                    </div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div id="headingFive" class="panel-heading" role="tab">
                    <h4 class="panel-title"><a class="collapsed" role="button" href="#collapseFive" data-toggle="collapse" data-parent="#accordion3"> What is Cash on Delivery? </a></h4>
                  </div>
                  <div id="collapseFive" class="panel-collapse collapse" role="tabpanel">
                    <div class="panel-body">
                      <p>If you are not comfortable making an online payment on Ecart.ae.com, you can opt for the Cash on Delivery (C-o-D) payment method instead. With C-o-D you can pay in cash at the time of actual delivery of the product at your doorstep, without requiring you to make any advance payment online.To avail the benefit of cash on delivery you have to pay extra amount of AED 5 across UAE region.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div id="shipping" class="tab-pane" role="tabpanel">
              <div class="__not__found">No Record Found</div>
            </div>
            <div id="refund" class="tab-pane" role="tabpanel">
              <div class="__not__found">No Record Found</div>
            </div>
            <div id="others" class="tab-pane" role="tabpanel">
              <div class="__not__found">No Record Found</div>
            </div>
          </div>
        </div>
        <h3>How would you like to contact us?</h3>
        <a class="btn1 btn btn-default" id="showLiveChat"> Live Chat</a> <a class="btn1 btn btn-default" href="<?php Mage::getBaseUrl(); ?>index.php/contacts/index/"> Email Us</a></div>
      <div class="col-sm-4">
        <section class="__recent__faq">
          <h2>Frequently Asked Questions</h2>
          <ul class="rightsidefaqs">
            <li><a href="#collapseEight" aria-controls="order" data-role="accordion">How do I know my order has been confirmed?</a></li>
            <li><a href="#collapseOne" aria-controls="order" >How do I check the current status of my orders?  </a></li>
            <li><a href="#collapseTwo" aria-controls="shopping">What is 'My Account'? How do I update my information? </a></li>
            <li><a href="#collapseNine" aria-controls="shopping">How does the delivery process work? </a></li>
            <li><a href="#collapseThree" aria-controls="shopping">Can I order a product that is 'Out of Stock'? </a></li>
            <li><a href="#collapseSix" aria-controls="payment">How do I pay using a credit?  </a></li>
            <li><a href="#collapseSeven" aria-controls="payment">Is it safe to use my credit on eCart.ae? </a></li>
            <li><a href="#collapseFour" aria-controls="payment">How do I pay for a eCart.ae purchase? </a></li>
            <li><a href="#collapseFive" aria-controls="payment">What is Cash on Delivery? </a></li>
            <li class="__more__question"><a href="#">View More Questions</a></li>
          </ul>
        </section>
            <section class="__customer__service">
                <h2>Customer Service</h2>
                <div class="__phone">Toll Free No <a href="#">800  42935</a></div>
            </section>
            <section class="__follow__us">
                <h2>Follow Us</h2>
                <div class="social clearfix">
                <a class="fb" href="http://www.facebook.com/ecart.ae" target="_blank"><i class="fa fa-facebook"></i></a>
                <a class="tw" href="https://twitter.com/MyeCart" target="_blank"><i class="fa fa-twitter"></i></a>
            <a class="gplus" href="https://plus.google.com/+EcartAe26" target="_blank"><i class="fa fa-google-plus"></i></a>
     <a class="linkedin" href="https://www.linkedin.com/company/ecart-ae" target="_blank"><i class="fa fa-linkedin"></i></a>
                </div>
            </section>
      </div>
    </div>
</section>


<script>
var rightsidefaqs = jQuery('.rightsidefaqs li a');
jQuery('.rightsidefaqs li a').click(function(event) {
	 event.preventDefault;
	
	 var attroflist = jQuery(this).attr('aria-controls')
	 jQuery('a[href^="#' + attroflist + '"]').trigger('click');
	 var hrefoflist = jQuery(this).attr('href');
	 //alert(hrefoflist);
	  jQuery('.tab-content a[href^="' + hrefoflist + '"]').trigger('click');
});

jQuery("#showLiveChat").click(function(){
    /* Act on the event */
    $zopim.livechat.button.show();
    $zopim.livechat.window.show();
    $zopim.livechat.bubble.show();
});
</script>