<div id="popup-window-mask" style="display:none;"></div>
<div id="tmcore_popup" class="product-configure-popup" style="display:none;">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head fieldset-legend" id="tmcore_popup_title"><?php echo Mage::helper('catalog')->__('Window') ?></h4>
            <a href="javascript:void(0)" class="close f-right" onclick="tmcoreWindow.onCloseBtn()"><?php echo Mage::helper('catalog')->__('Close') ?></a>
        </div>
        <div id="tmcore_popup_content" class="content"></div>
        <div class="buttons-set a-right">
            <button type="button" class="scalable close" onclick="tmcoreWindow.onCloseBtn()"><span><span><span><?php echo Mage::helper('catalog')->__('Close') ?></span></span></span></button>
        </div>
    </div>
</div>
