<?php $_productCollection = $this->getLoadedRelProduct();
$_helper = $this->helper('catalog/output'); ?>
<section class="desktop arrow-sides" id="users_brought_products">
  <div class="sectiontitle">
    <h2><span>Customers who bought this also bought</span></h2>
  </div>
  <div data-items="4" id="bestselingproducts" class="columnslider">      
                      <?php foreach ($_productCollection as $_products): ?>
                        <?php $_product = Mage::getModel('catalog/product')->load($_products); ?>
                            <div class="col-box" id="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                            <a href="<?php echo $_product->getProductUrl() ?>">
                                <?php if (date("Y-m-d") >= substr($_product->getNewsFromDate(), 0, 10) && date("Y-m-d") <= substr($_product->getNewsToDate(), 0, 10)) {
                                 ?>


                                      <span class="new">new</span>
                                  <?php } ?>
                                  <div class="img-box"><div class="abs_center"><!-- <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"> -->
                                  <?php $_imgSize = 210; ?>
                                        <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($_imgSize); ?>"
                                        alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                  <!-- </a> --></div></div>
                                <div class="bottom-area">
                                    <h4><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h4>
                                    <div class="ratings">
                                         <div class="rating-box">
                                              <div class="rating" style="width:<?php echo $summaryData['rating_summary']; ?>%"></div>  
                                          </div>
                                    </div>
                                    <div class="price"><?php echo number_format($_product->getPrice(), '1', '.', ','); ?><i>AED</i></div>
                                </div>
                              </a> 
                            </div>
                             <?php endforeach ?>
                        </div>
                     
  

</section>
