<section class="desktop arrow-sides" id="users_brought_products">
  <div class="sectiontitle">
    <h2><span>Customers who bought this also bought</span></h2>
  </div>
  <div data-items="4" id="bestselingproducts" class="columnslider owl-carousel owl-theme owl-responsive-1025 owl-loaded">
    <div class="owl-stage-outer">
      <div class="owl-stage" style="transform: translate3d(0px, 0px, 0px); transition: all 0s ease 0s; width: 1740px;">
        <div class="owl-item active" style="width: 270px; margin-right: 20px;">
          <div class="col-box"><a href="#"> <span class="new">new</span>
            <div class="img-box">
              <div class="abs_center"><img alt="" src="images/universal-car-wishield.jpg"></div>
            </div>
            <div class="bottom-area">
              <h4>Universal Car Windshield</h4>
              <div class="rating"></div>
              <div class="price">20<i>AED</i></div>
            </div>
            </a> </div>
        </div>
        <div class="owl-item active" style="width: 270px; margin-right: 20px;">
          <div class="col-box"><a href="#"> <span class="new">new</span>
            <div class="img-box">
              <div class="abs_center"><img alt="" src="images/universal-car-wishield.jpg"></div>
            </div>
            <div class="bottom-area">
              <h4>Universal Car Windshield</h4>
              <div class="rating"></div>
              <div class="price">20<i>AED</i></div>
            </div>
            </a> </div>
        </div>
        <div class="owl-item active" style="width: 270px; margin-right: 20px;">
          <div class="col-box"><a href="#">
            <div class="img-box">
              <div class="abs_center"><img alt="" src="images/bodysuspender.jpg"></div>
            </div>
            <div class="bottom-area">
              <h4>Baby Suspenders</h4>
              <div class="rating"></div>
              <div class="price">20<i>AED</i></div>
            </div>
            </a> </div>
        </div>
        <div class="owl-item active" style="width: 270px; margin-right: 20px;">
          <div class="col-box"><a href="#">
            <div class="img-box">
              <div class="abs_center"><img alt="" src="images/iphonecase.jpg"></div>
            </div>
            <div class="bottom-area">
              <h4>Phone Case iPhone 6 Plus</h4>
              <div class="rating"></div>
              <div class="price">20<i>AED</i></div>
            </div>
            </a> </div>
        </div>
        <div class="owl-item" style="width: 270px; margin-right: 20px;">
          <div class="col-box"><a href="#">
            <div class="img-box">
              <div class="abs_center"><img alt="" src="images/mini-bluetooth-speaker.jpg"></div>
            </div>
            <div class="bottom-area">
              <h4>Mini Bluetooth Speakers</h4>
              <div class="rating"></div>
              <div class="price">20<i>AED</i></div>
            </div>
            </a> </div>
        </div>
        <div class="owl-item" style="width: 270px; margin-right: 20px;">
          <div class="col-box"><a href="#">
            <div class="img-box">
              <div class="abs_center"><img alt="" src="images/mini-bluetooth-speaker.jpg"></div>
            </div>
            <div class="bottom-area">
              <h4>Mini Bluetooth Speakers</h4>
              <div class="rating"></div>
              <div class="price">20<i>AED</i></div>
            </div>
            </a> </div>
        </div>
      </div>
    </div>
    <div class="owl-controls">
      <div class="owl-nav">
        <div class="owl-prev" style="">prev</div>
        <div class="owl-next" style="">next</div>
      </div>
      <div style="display: none;" class="owl-dots"></div>
    </div>
  </div>
</section>
