<?php 
    $store = Mage::app()->getStore()->getId();
    if (Mage::getStoreConfig('shopbybrand/feature_brand_flexibebox/display_featured_brand',$store)) :    
?>

<?php
    $featuredBrands = $this->getFeaturedBrands();
    $showAsSlider = Mage::getStoreConfig('shopbybrand/feature_brand_flexibebox/show_featured_brand_as_slider',$store);
    $logo_width = Mage::getStoreConfig('shopbybrand/brand_list/brand_logo_width',$store);
    $logo_height = Mage::getStoreConfig('shopbybrand/brand_list/brand_logo_height',$store);
    $brandWidth = $logo_width +50;
?>

<?php if (count($featuredBrands)): ?>
<?php if (!$showAsSlider) :  ?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/sliderstyle.css'); ?>" media="all" />

<style type="text/css" media="screen">
    .ca-container{
        height: <?php echo $logo_height+35;?>px;
    }    
    .ca-container .brand-logo {
        height: <?php echo $logo_height;?>px;
    }
    .ca-item{
        width:<?php echo $brandWidth;?>px;
    }
</style>

<section id="sponsors">
<div class="sectiontitle">
				<h2><span>Our Brands</span></h2>
				<a href="brand/">View More Brands</a>
			</div>
   <?php /*?> <div class="shopbybrand-title">
        <h1><?php echo $this->__('Featured Brands');?></h1>
    </div><?php */?>

        <div class="row">
            <?php 
                $i = 0;
                foreach ($featuredBrands as $featuredBrand) : 
                    $i++;
                    $path = 'brands/thumbnail' . DS . $featuredBrand->getId();
                    $img = Mage::helper('shopbybrand/image')
                        ->init($featuredBrand, $path)->resizeThumbnail($logo_width, $logo_height);
            ?>
            <div class=" col-sm-2 caItem ca-item-<?php echo $i;?>">
              
                    <a href="<?php echo $this->getBrandUrl($featuredBrand); ?>">
                        <div class="brand-logo sponsorlogo">
                            <img src="<?php echo $img; ?>" />
                        </div>
                        <div style="display: block;">
                        <?php //echo $featuredBrand->getName(); ?>
                        </div>
                    </a>
               
            </div>
            <?php endforeach;?>
        </div>

    <script type="text/javascript">
        var brandWidth = <?php echo $brandWidth;?>;
        var running = false;
        
        var countFeaturedBrands = <?php echo count($featuredBrands);?>;
        var featuredbrandsWidth = $$('.featuredbrands').first().offsetWidth -50;
        var numberofbrand = Math.floor(featuredbrandsWidth/brandWidth);
        numberofbrand = (numberofbrand<=countFeaturedBrands)?numberofbrand:countFeaturedBrands;
        $('ca-container').style.width = numberofbrand*brandWidth +"px";
        window.onresize = brandresize;
        function brandresize(){
            featuredbrandsWidth = $$('.featuredbrands').first().offsetWidth  -50;
            numberofbrand = Math.floor(featuredbrandsWidth/brandWidth);
            numberofbrand = (numberofbrand<=countFeaturedBrands)?numberofbrand:countFeaturedBrands;
            $('ca-container').style.width = numberofbrand*brandWidth +"px";
        }
    </script>


</section>
<?php else:?>
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/shopbybrand/templates/default/sliderstyle.css'); ?>" media="all" />

<style type="text/css" media="screen">
    .ca-container{
        height: <?php echo $logo_height+35;?>px;
    }    
    .ca-container .brand-logo {
        height: <?php echo $logo_height;?>px;
    }
    .ca-item{
        width:<?php echo $brandWidth;?>px;
    }
</style>


<?php endif; ?>
<?php endif; ?>

<?php endif; ?>
